fix(gist): fixed the lost of indentation
sunt-programator/CodeIT pull request #226
Opened 2021-06-28 00:54 UTC by aplatanado

This is a legacy bug from: dillonzq/LoveIt#472
The embedded gist doesn't show the indentations spaces.

2021-06-29 06:30 UTC, victor-pogor requested changes

2021-06-29 10:31 UTC, aplatanado commented on assets/css/_partial/_single/_code.scss
> +.gist {
Yes. It's done. I don't know how I couldn't see it

2021-06-30 18:31 UTC, victor-pogor approved these changes

2021-06-30 18:32 UTC, victor-pogor commented
@all-contributors please add @aplatanado for code

2021-07-05 17:33 UTC, merged